### ISSUE TITLE
Try out `graphql-code-generator`

### ISSUE THREAD

**Issue by edd** [vegaprotocol/api#211]
https://www.graphql-code-generator.com/ can generate client libraries from a Graphql schema. in https://github.com/vegaprotocol/console we use Apollo Codegen (https://www.npmjs.com/package/apollo#code-generation) but Graphql Code Generator looks like it gives us some more flexibility (specifically react hooks without a client library, or an urql client)

# Spike
- [ ] Create a branch using graphql-code-generator to create a react-apollo-hooks typescript library from the schema

If that looks reasonable, we can expand with other clients as required (urql would be a smart choice, but also react-query-hooks for the no-apollo-but-still-react crowd)

**Comment by ashleyvega** [comment]
@edd What plugins would you like? I've added `@graphql-codegen/typescript`.

Would `@graphql-codegen/typescript-operations` be useful:
> Generate client specific TypeScript types (query, mutation, subscription, fragment)

https://www.graphql-code-generator.com/docs/plugins/index

**Comment by edd** [comment]
Good start. Also:
- typescript-apollo-client-helpers
- typescript-react-apollo
- typescript-graphql-files-modules


Taking a guess here really.

**Comment by ashleyvega** [comment]
`typescript-graphql-files-modules` does not produce any output for the current `schema.graphql`, but I've added the other 2 plugins.

I've kept the files separate, but they can be merged into fewer files if that's convenient.
