### ISSUE TITLE
Update Core API auto-generated documentation

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/api#395]
With the addition of the datanode we now require that the functionallity is added/enabled in order to create the auto-generated documentation for Core’s APIs:
- rest
- grpc

This is in order to be able to give us and the community a guide as to the API specification

Questions to cover might be:
- Which repo should `core-grpc-doc.json` and `datanode-grpc-doc.json` [see existing](https://github.com/vegaprotocol/api/tree/develop/grpc/doc) go in?
  - [ ] protos
  - [ ] some-sdk-doc-new-repo
  - [ ] other

For reference, `swagger.json` is in the [protos repo](https://github.com/vegaprotocol/protos/blob/develop/swagger/vega/api/trading.swagger.json) and is copied in to the [API repo](https://github.com/vegaprotocol/api/blob/develop/rest/api/trading.swagger.json).

Note: This question is relevant whether we are generating with Docusaurs (see [vegaprotocol/documentation](https://github.com/vegaprotocol/documentation/)) or The Old System [vegaprotocol/docs](https://github.com/vegaprotocol/docs))

**Comment by ashleyvega** [comment]
Replaced by
- https://github.com/vegaprotocol/sdk-docs/pull/6
- https://github.com/vegaprotocol/docs/issues/289, https://github.com/vegaprotocol/docs/pull/293
